apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-server-deployment
spec:
  replicas: 3 # Menjalankan 3 instansi sekaligus
  selector:
    matchLabels:
      app: discovery-server
  template:
    metadata:
      labels:
        app: discovery-server
    spec:
      containers:
        - name: discovery-server
          image: discovery-server:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8761