server:
  port: 8081

spring:
  application:
    name: RESTAURANT-SERVICE

  datasource:
    url: jdbc:postgresql://postgres-db:5432/food_delivery_db
    username: M2m2
    password: M2m4
    driver-class-name: org.postgresql.Driver

  kafka:
    listener:
      observation-enabled: true

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: redis
      port: 6379
    cache:
      type: redis
      redis:
        time-to-live: 600000

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://openzipkin:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true




#
#  h2:
#    console:
#      enabled: true
#  datasource:
#      url: jdbc:h2:mem:M@
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create

