server:
  port: 8084

spring:
  application:
    name: ORDER-SERVICE

  datasource:
    url: jdbc:postgresql://postgres-db:5432/food_delivery_db
    username: M2m2
    password: M2m4

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    template:
      observation-enabled: true
    listener:
      observation-enabled: true

  management:
    tracing:
      sampling:
        probability: 1.0
    zipkin:
      tracing:
        endpoint: http://openzipkin:9411/api/v2/spans
    endpoints:
      web:
        exposure:
          include: "*"

services:
  driver:
    url: http://driver-service:8082/public/drivers
  restaurant:
    url: http://restaurant-service:8081/public/restaurants

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

resilience4j:
  circuitbreaker:
    instances:
      driverServiceCB:
        sliding-window-size: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10000ms
        permitted-number-of-calls-in-half-open-state: 2
      restaurantServiceCB:
        sliding-window-size: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10000ms
  timelimiter:
    instances:
      driverServiceCB:
        timeout-duration: 10s
      restaurantServiceCB:
        timeout-duration: 10s


#  h2:
#    console:
#      enabled: true
#  datasource:
#    url: jdbc:h2:mem:M@
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create



