apiVersion: apps/v1
kind: Deployment
metadata:
  name: driver-service-deployment
spec:
  replicas: 3 # Menjalankan 3 instansi sekaligus
  selector:
    matchLabels:
      app: driver-service
  template:
    metadata:
      labels:
        app: driver-service
    spec:
      containers:
        - name: driver-service
          image: driver-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082